### ISSUE TITLE
"upload-software-dfu" and "upload-firmware-dfu" are a bit long for target names

### ISSUE THREAD

**Issue by eriknyquist** [01org/CODK-A#3]
Maybe not a big deal, would like to hear what others think though. So in the Makefile here we have the following targets;

```
upload-firmware-dfu
upload-software-dfu 
upload-firmware-jtag 
upload-software-jtag
```

Given that, if our plans succeed (_evil laugh_) people will be typing "make upload-software-dfu" many, many times in the future, can we make it a little easier for them and remove some of those uneccessary characters?

```
upload-fw-dfu
upload-sw-dfu
upload-fw-jtag
upload-sw-jtag
```

**Comment by calvinatintel** [comment]
How about using tab completion?
`make upload-s<tab>` completes to `make upload-software-`

**Comment by eriknyquist** [comment]
Yeah, there are a few ways a user could work around our long names. Tab completion is one, but the behaviour (for Makefile targets, at least) is different there depending on shell and OS. But, because there are so many ways then maybe it doesn't matter too much.

**Comment by calvinatintel** [comment]
WONTFIX!

**Comment by bigdinotech** [comment]
How about `upload-[cpu_target]-dfu/jtag` ?

That way they know which core they are flashing
